# Generated by Django 5.2.1 on 2025-05-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecwapp', '0002_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=20),
        ),
    ]
