# Generated by Django 5.2.1 on 2025-06-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecwapp', '0006_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='contect',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=25)),
                ('phone_no', models.CharField(default='', max_length=15)),
                ('query', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
