# Generated by Django 5.2.1 on 2025-06-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecwapp', '0007_contect'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('selected_items', models.CharField(default='', max_length=300)),
                ('name', models.CharField(default='', max_length=20)),
                ('phone_no', models.CharField(default='', max_length=10)),
                ('address', models.CharField(default='', max_length=300)),
                ('city', models.CharField(default='', max_length=30)),
                ('zip_code', models.CharField(default='', max_length=10)),
                ('payment_method', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
