# Generated by Django 5.2.1 on 2025-06-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecwapp', '0008_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
