# Generated by Django 5.2.1 on 2025-06-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecwapp', '0009_product_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='orders',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
