# Generated by Django 5.2.1 on 2025-08-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecwapp', '0011_upitransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='phone_no',
            field=models.CharField(default='', max_length=15),
        ),
    ]
