# Generated by Django 5.2.1 on 2025-08-25 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecwapp', '0012_alter_orders_phone_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_pic', models.ImageField(default='', upload_to='myimages/')),
                ('address', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=33)),
                ('phone_no', models.CharField(default='', max_length=15)),
                ('onwer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
