# Generated by Django 5.2.1 on 2025-08-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecwapp', '0014_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='upitransaction',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='upitransaction',
            name='verify',
            field=models.CharField(default='', max_length=50),
        ),
    ]
