# Generated by Django 5.2.1 on 2025-08-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecwapp', '0015_upitransaction_name_upitransaction_verify'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='', max_length=30)),
                ('the_review', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
