# Generated by Django 5.2.1 on 2025-08-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecwapp', '0016_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
